import numpy as np

from _sparsepy import _Dict_uint8_t_uint8_t
from _sparsepy import _Dict_uint8_t_uint16_t
from _sparsepy import _Dict_uint8_t_uint32_t
from _sparsepy import _Dict_uint8_t_uint64_t
from _sparsepy import _Dict_uint8_t_int8_t
from _sparsepy import _Dict_uint8_t_int16_t
from _sparsepy import _Dict_uint8_t_int32_t
from _sparsepy import _Dict_uint8_t_int64_t
from _sparsepy import _Dict_uint8_t_float
from _sparsepy import _Dict_uint8_t_double
from _sparsepy import _Dict_uint8_t_bool
from _sparsepy import _Dict_uint16_t_uint8_t
from _sparsepy import _Dict_uint16_t_uint16_t
from _sparsepy import _Dict_uint16_t_uint32_t
from _sparsepy import _Dict_uint16_t_uint64_t
from _sparsepy import _Dict_uint16_t_int8_t
from _sparsepy import _Dict_uint16_t_int16_t
from _sparsepy import _Dict_uint16_t_int32_t
from _sparsepy import _Dict_uint16_t_int64_t
from _sparsepy import _Dict_uint16_t_float
from _sparsepy import _Dict_uint16_t_double
from _sparsepy import _Dict_uint16_t_bool
from _sparsepy import _Dict_uint32_t_uint8_t
from _sparsepy import _Dict_uint32_t_uint16_t
from _sparsepy import _Dict_uint32_t_uint32_t
from _sparsepy import _Dict_uint32_t_uint64_t
from _sparsepy import _Dict_uint32_t_int8_t
from _sparsepy import _Dict_uint32_t_int16_t
from _sparsepy import _Dict_uint32_t_int32_t
from _sparsepy import _Dict_uint32_t_int64_t
from _sparsepy import _Dict_uint32_t_float
from _sparsepy import _Dict_uint32_t_double
from _sparsepy import _Dict_uint32_t_bool
from _sparsepy import _Dict_uint64_t_uint8_t
from _sparsepy import _Dict_uint64_t_uint16_t
from _sparsepy import _Dict_uint64_t_uint32_t
from _sparsepy import _Dict_uint64_t_uint64_t
from _sparsepy import _Dict_uint64_t_int8_t
from _sparsepy import _Dict_uint64_t_int16_t
from _sparsepy import _Dict_uint64_t_int32_t
from _sparsepy import _Dict_uint64_t_int64_t
from _sparsepy import _Dict_uint64_t_float
from _sparsepy import _Dict_uint64_t_double
from _sparsepy import _Dict_uint64_t_bool
from _sparsepy import _Dict_int8_t_uint8_t
from _sparsepy import _Dict_int8_t_uint16_t
from _sparsepy import _Dict_int8_t_uint32_t
from _sparsepy import _Dict_int8_t_uint64_t
from _sparsepy import _Dict_int8_t_int8_t
from _sparsepy import _Dict_int8_t_int16_t
from _sparsepy import _Dict_int8_t_int32_t
from _sparsepy import _Dict_int8_t_int64_t
from _sparsepy import _Dict_int8_t_float
from _sparsepy import _Dict_int8_t_double
from _sparsepy import _Dict_int8_t_bool
from _sparsepy import _Dict_int16_t_uint8_t
from _sparsepy import _Dict_int16_t_uint16_t
from _sparsepy import _Dict_int16_t_uint32_t
from _sparsepy import _Dict_int16_t_uint64_t
from _sparsepy import _Dict_int16_t_int8_t
from _sparsepy import _Dict_int16_t_int16_t
from _sparsepy import _Dict_int16_t_int32_t
from _sparsepy import _Dict_int16_t_int64_t
from _sparsepy import _Dict_int16_t_float
from _sparsepy import _Dict_int16_t_double
from _sparsepy import _Dict_int16_t_bool
from _sparsepy import _Dict_int32_t_uint8_t
from _sparsepy import _Dict_int32_t_uint16_t
from _sparsepy import _Dict_int32_t_uint32_t
from _sparsepy import _Dict_int32_t_uint64_t
from _sparsepy import _Dict_int32_t_int8_t
from _sparsepy import _Dict_int32_t_int16_t
from _sparsepy import _Dict_int32_t_int32_t
from _sparsepy import _Dict_int32_t_int64_t
from _sparsepy import _Dict_int32_t_float
from _sparsepy import _Dict_int32_t_double
from _sparsepy import _Dict_int32_t_bool
from _sparsepy import _Dict_int64_t_uint8_t
from _sparsepy import _Dict_int64_t_uint16_t
from _sparsepy import _Dict_int64_t_uint32_t
from _sparsepy import _Dict_int64_t_uint64_t
from _sparsepy import _Dict_int64_t_int8_t
from _sparsepy import _Dict_int64_t_int16_t
from _sparsepy import _Dict_int64_t_int32_t
from _sparsepy import _Dict_int64_t_int64_t
from _sparsepy import _Dict_int64_t_float
from _sparsepy import _Dict_int64_t_double
from _sparsepy import _Dict_int64_t_bool

_types = {
	(np.dtype("u1"), np.dtype("u1")) : _Dict_uint8_t_uint8_t,
	(np.dtype("u1"), np.dtype("u2")) : _Dict_uint8_t_uint16_t,
	(np.dtype("u1"), np.dtype("u4")) : _Dict_uint8_t_uint32_t,
	(np.dtype("u1"), np.dtype("u8")) : _Dict_uint8_t_uint64_t,
	(np.dtype("u1"), np.dtype("i1")) : _Dict_uint8_t_int8_t,
	(np.dtype("u1"), np.dtype("i2")) : _Dict_uint8_t_int16_t,
	(np.dtype("u1"), np.dtype("i4")) : _Dict_uint8_t_int32_t,
	(np.dtype("u1"), np.dtype("i8")) : _Dict_uint8_t_int64_t,
	(np.dtype("u1"), np.dtype("f4")) : _Dict_uint8_t_float,
	(np.dtype("u1"), np.dtype("f8")) : _Dict_uint8_t_double,
	(np.dtype("u1"), np.dtype("?")) : _Dict_uint8_t_bool,
	(np.dtype("u2"), np.dtype("u1")) : _Dict_uint16_t_uint8_t,
	(np.dtype("u2"), np.dtype("u2")) : _Dict_uint16_t_uint16_t,
	(np.dtype("u2"), np.dtype("u4")) : _Dict_uint16_t_uint32_t,
	(np.dtype("u2"), np.dtype("u8")) : _Dict_uint16_t_uint64_t,
	(np.dtype("u2"), np.dtype("i1")) : _Dict_uint16_t_int8_t,
	(np.dtype("u2"), np.dtype("i2")) : _Dict_uint16_t_int16_t,
	(np.dtype("u2"), np.dtype("i4")) : _Dict_uint16_t_int32_t,
	(np.dtype("u2"), np.dtype("i8")) : _Dict_uint16_t_int64_t,
	(np.dtype("u2"), np.dtype("f4")) : _Dict_uint16_t_float,
	(np.dtype("u2"), np.dtype("f8")) : _Dict_uint16_t_double,
	(np.dtype("u2"), np.dtype("?")) : _Dict_uint16_t_bool,
	(np.dtype("u4"), np.dtype("u1")) : _Dict_uint32_t_uint8_t,
	(np.dtype("u4"), np.dtype("u2")) : _Dict_uint32_t_uint16_t,
	(np.dtype("u4"), np.dtype("u4")) : _Dict_uint32_t_uint32_t,
	(np.dtype("u4"), np.dtype("u8")) : _Dict_uint32_t_uint64_t,
	(np.dtype("u4"), np.dtype("i1")) : _Dict_uint32_t_int8_t,
	(np.dtype("u4"), np.dtype("i2")) : _Dict_uint32_t_int16_t,
	(np.dtype("u4"), np.dtype("i4")) : _Dict_uint32_t_int32_t,
	(np.dtype("u4"), np.dtype("i8")) : _Dict_uint32_t_int64_t,
	(np.dtype("u4"), np.dtype("f4")) : _Dict_uint32_t_float,
	(np.dtype("u4"), np.dtype("f8")) : _Dict_uint32_t_double,
	(np.dtype("u4"), np.dtype("?")) : _Dict_uint32_t_bool,
	(np.dtype("u8"), np.dtype("u1")) : _Dict_uint64_t_uint8_t,
	(np.dtype("u8"), np.dtype("u2")) : _Dict_uint64_t_uint16_t,
	(np.dtype("u8"), np.dtype("u4")) : _Dict_uint64_t_uint32_t,
	(np.dtype("u8"), np.dtype("u8")) : _Dict_uint64_t_uint64_t,
	(np.dtype("u8"), np.dtype("i1")) : _Dict_uint64_t_int8_t,
	(np.dtype("u8"), np.dtype("i2")) : _Dict_uint64_t_int16_t,
	(np.dtype("u8"), np.dtype("i4")) : _Dict_uint64_t_int32_t,
	(np.dtype("u8"), np.dtype("i8")) : _Dict_uint64_t_int64_t,
	(np.dtype("u8"), np.dtype("f4")) : _Dict_uint64_t_float,
	(np.dtype("u8"), np.dtype("f8")) : _Dict_uint64_t_double,
	(np.dtype("u8"), np.dtype("?")) : _Dict_uint64_t_bool,
	(np.dtype("i1"), np.dtype("u1")) : _Dict_int8_t_uint8_t,
	(np.dtype("i1"), np.dtype("u2")) : _Dict_int8_t_uint16_t,
	(np.dtype("i1"), np.dtype("u4")) : _Dict_int8_t_uint32_t,
	(np.dtype("i1"), np.dtype("u8")) : _Dict_int8_t_uint64_t,
	(np.dtype("i1"), np.dtype("i1")) : _Dict_int8_t_int8_t,
	(np.dtype("i1"), np.dtype("i2")) : _Dict_int8_t_int16_t,
	(np.dtype("i1"), np.dtype("i4")) : _Dict_int8_t_int32_t,
	(np.dtype("i1"), np.dtype("i8")) : _Dict_int8_t_int64_t,
	(np.dtype("i1"), np.dtype("f4")) : _Dict_int8_t_float,
	(np.dtype("i1"), np.dtype("f8")) : _Dict_int8_t_double,
	(np.dtype("i1"), np.dtype("?")) : _Dict_int8_t_bool,
	(np.dtype("i2"), np.dtype("u1")) : _Dict_int16_t_uint8_t,
	(np.dtype("i2"), np.dtype("u2")) : _Dict_int16_t_uint16_t,
	(np.dtype("i2"), np.dtype("u4")) : _Dict_int16_t_uint32_t,
	(np.dtype("i2"), np.dtype("u8")) : _Dict_int16_t_uint64_t,
	(np.dtype("i2"), np.dtype("i1")) : _Dict_int16_t_int8_t,
	(np.dtype("i2"), np.dtype("i2")) : _Dict_int16_t_int16_t,
	(np.dtype("i2"), np.dtype("i4")) : _Dict_int16_t_int32_t,
	(np.dtype("i2"), np.dtype("i8")) : _Dict_int16_t_int64_t,
	(np.dtype("i2"), np.dtype("f4")) : _Dict_int16_t_float,
	(np.dtype("i2"), np.dtype("f8")) : _Dict_int16_t_double,
	(np.dtype("i2"), np.dtype("?")) : _Dict_int16_t_bool,
	(np.dtype("i4"), np.dtype("u1")) : _Dict_int32_t_uint8_t,
	(np.dtype("i4"), np.dtype("u2")) : _Dict_int32_t_uint16_t,
	(np.dtype("i4"), np.dtype("u4")) : _Dict_int32_t_uint32_t,
	(np.dtype("i4"), np.dtype("u8")) : _Dict_int32_t_uint64_t,
	(np.dtype("i4"), np.dtype("i1")) : _Dict_int32_t_int8_t,
	(np.dtype("i4"), np.dtype("i2")) : _Dict_int32_t_int16_t,
	(np.dtype("i4"), np.dtype("i4")) : _Dict_int32_t_int32_t,
	(np.dtype("i4"), np.dtype("i8")) : _Dict_int32_t_int64_t,
	(np.dtype("i4"), np.dtype("f4")) : _Dict_int32_t_float,
	(np.dtype("i4"), np.dtype("f8")) : _Dict_int32_t_double,
	(np.dtype("i4"), np.dtype("?")) : _Dict_int32_t_bool,
	(np.dtype("i8"), np.dtype("u1")) : _Dict_int64_t_uint8_t,
	(np.dtype("i8"), np.dtype("u2")) : _Dict_int64_t_uint16_t,
	(np.dtype("i8"), np.dtype("u4")) : _Dict_int64_t_uint32_t,
	(np.dtype("i8"), np.dtype("u8")) : _Dict_int64_t_uint64_t,
	(np.dtype("i8"), np.dtype("i1")) : _Dict_int64_t_int8_t,
	(np.dtype("i8"), np.dtype("i2")) : _Dict_int64_t_int16_t,
	(np.dtype("i8"), np.dtype("i4")) : _Dict_int64_t_int32_t,
	(np.dtype("i8"), np.dtype("i8")) : _Dict_int64_t_int64_t,
	(np.dtype("i8"), np.dtype("f4")) : _Dict_int64_t_float,
	(np.dtype("i8"), np.dtype("f8")) : _Dict_int64_t_double,
	(np.dtype("i8"), np.dtype("?")) : _Dict_int64_t_bool,
}
