#include "getpy.cpp"

#include <pybind11/pybind11.h>

PYBIND11_MODULE(_getpy, m) {
    m.doc() = "A Fast and Memory Efficient Hash Map for Python";

    declare_dict_default<uint32_t, uint8_t>(m, "Dict_uint32_uint8");
    declare_dict_default<uint32_t, uint16_t>(m, "Dict_uint32_uint16");
    declare_dict_default<uint32_t, uint32_t>(m, "Dict_uint32_uint32");
    declare_dict_default<uint32_t, uint64_t>(m, "Dict_uint32_uint64");
    declare_dict_default<uint32_t, int8_t>(m, "Dict_uint32_int8");
    declare_dict_default<uint32_t, int16_t>(m, "Dict_uint32_int16");
    declare_dict_default<uint32_t, int32_t>(m, "Dict_uint32_int32");
    declare_dict_default<uint32_t, int64_t>(m, "Dict_uint32_int64");
    declare_dict_default<uint32_t, float>(m, "Dict_uint32_float32");
    declare_dict_default<uint32_t, double>(m, "Dict_uint32_float64");
    declare_dict_bitwise<uint32_t, std::array<char,4>>(m, "Dict_uint32_byteset4");
    declare_dict_bitwise<uint32_t, std::array<char,8>>(m, "Dict_uint32_byteset8");
    declare_dict_bitwise<uint32_t, std::array<char,12>>(m, "Dict_uint32_byteset12");
    declare_dict_bitwise<uint32_t, std::array<char,16>>(m, "Dict_uint32_byteset16");
    declare_dict_default<uint64_t, uint8_t>(m, "Dict_uint64_uint8");
    declare_dict_default<uint64_t, uint16_t>(m, "Dict_uint64_uint16");
    declare_dict_default<uint64_t, uint32_t>(m, "Dict_uint64_uint32");
    declare_dict_default<uint64_t, uint64_t>(m, "Dict_uint64_uint64");
    declare_dict_default<uint64_t, int8_t>(m, "Dict_uint64_int8");
    declare_dict_default<uint64_t, int16_t>(m, "Dict_uint64_int16");
    declare_dict_default<uint64_t, int32_t>(m, "Dict_uint64_int32");
    declare_dict_default<uint64_t, int64_t>(m, "Dict_uint64_int64");
    declare_dict_default<uint64_t, float>(m, "Dict_uint64_float32");
    declare_dict_default<uint64_t, double>(m, "Dict_uint64_float64");
    declare_dict_bitwise<uint64_t, std::array<char,4>>(m, "Dict_uint64_byteset4");
    declare_dict_bitwise<uint64_t, std::array<char,8>>(m, "Dict_uint64_byteset8");
    declare_dict_bitwise<uint64_t, std::array<char,12>>(m, "Dict_uint64_byteset12");
    declare_dict_bitwise<uint64_t, std::array<char,16>>(m, "Dict_uint64_byteset16");
    declare_dict_default<int32_t, uint8_t>(m, "Dict_int32_uint8");
    declare_dict_default<int32_t, uint16_t>(m, "Dict_int32_uint16");
    declare_dict_default<int32_t, uint32_t>(m, "Dict_int32_uint32");
    declare_dict_default<int32_t, uint64_t>(m, "Dict_int32_uint64");
    declare_dict_default<int32_t, int8_t>(m, "Dict_int32_int8");
    declare_dict_default<int32_t, int16_t>(m, "Dict_int32_int16");
    declare_dict_default<int32_t, int32_t>(m, "Dict_int32_int32");
    declare_dict_default<int32_t, int64_t>(m, "Dict_int32_int64");
    declare_dict_default<int32_t, float>(m, "Dict_int32_float32");
    declare_dict_default<int32_t, double>(m, "Dict_int32_float64");
    declare_dict_bitwise<int32_t, std::array<char,4>>(m, "Dict_int32_byteset4");
    declare_dict_bitwise<int32_t, std::array<char,8>>(m, "Dict_int32_byteset8");
    declare_dict_bitwise<int32_t, std::array<char,12>>(m, "Dict_int32_byteset12");
    declare_dict_bitwise<int32_t, std::array<char,16>>(m, "Dict_int32_byteset16");
    declare_dict_default<int64_t, uint8_t>(m, "Dict_int64_uint8");
    declare_dict_default<int64_t, uint16_t>(m, "Dict_int64_uint16");
    declare_dict_default<int64_t, uint32_t>(m, "Dict_int64_uint32");
    declare_dict_default<int64_t, uint64_t>(m, "Dict_int64_uint64");
    declare_dict_default<int64_t, int8_t>(m, "Dict_int64_int8");
    declare_dict_default<int64_t, int16_t>(m, "Dict_int64_int16");
    declare_dict_default<int64_t, int32_t>(m, "Dict_int64_int32");
    declare_dict_default<int64_t, int64_t>(m, "Dict_int64_int64");
    declare_dict_default<int64_t, float>(m, "Dict_int64_float32");
    declare_dict_default<int64_t, double>(m, "Dict_int64_float64");
    declare_dict_bitwise<int64_t, std::array<char,4>>(m, "Dict_int64_byteset4");
    declare_dict_bitwise<int64_t, std::array<char,8>>(m, "Dict_int64_byteset8");
    declare_dict_bitwise<int64_t, std::array<char,12>>(m, "Dict_int64_byteset12");
    declare_dict_bitwise<int64_t, std::array<char,16>>(m, "Dict_int64_byteset16");
    declare_dict_default<std::array<char,4>, uint8_t>(m, "Dict_byteset4_uint8");
    declare_dict_default<std::array<char,4>, uint16_t>(m, "Dict_byteset4_uint16");
    declare_dict_default<std::array<char,4>, uint32_t>(m, "Dict_byteset4_uint32");
    declare_dict_default<std::array<char,4>, uint64_t>(m, "Dict_byteset4_uint64");
    declare_dict_default<std::array<char,4>, int8_t>(m, "Dict_byteset4_int8");
    declare_dict_default<std::array<char,4>, int16_t>(m, "Dict_byteset4_int16");
    declare_dict_default<std::array<char,4>, int32_t>(m, "Dict_byteset4_int32");
    declare_dict_default<std::array<char,4>, int64_t>(m, "Dict_byteset4_int64");
    declare_dict_default<std::array<char,4>, float>(m, "Dict_byteset4_float32");
    declare_dict_default<std::array<char,4>, double>(m, "Dict_byteset4_float64");
    declare_dict_bitwise<std::array<char,4>, std::array<char,4>>(m, "Dict_byteset4_byteset4");
    declare_dict_bitwise<std::array<char,4>, std::array<char,8>>(m, "Dict_byteset4_byteset8");
    declare_dict_bitwise<std::array<char,4>, std::array<char,12>>(m, "Dict_byteset4_byteset12");
    declare_dict_bitwise<std::array<char,4>, std::array<char,16>>(m, "Dict_byteset4_byteset16");
    declare_dict_default<std::array<char,8>, uint8_t>(m, "Dict_byteset8_uint8");
    declare_dict_default<std::array<char,8>, uint16_t>(m, "Dict_byteset8_uint16");
    declare_dict_default<std::array<char,8>, uint32_t>(m, "Dict_byteset8_uint32");
    declare_dict_default<std::array<char,8>, uint64_t>(m, "Dict_byteset8_uint64");
    declare_dict_default<std::array<char,8>, int8_t>(m, "Dict_byteset8_int8");
    declare_dict_default<std::array<char,8>, int16_t>(m, "Dict_byteset8_int16");
    declare_dict_default<std::array<char,8>, int32_t>(m, "Dict_byteset8_int32");
    declare_dict_default<std::array<char,8>, int64_t>(m, "Dict_byteset8_int64");
    declare_dict_default<std::array<char,8>, float>(m, "Dict_byteset8_float32");
    declare_dict_default<std::array<char,8>, double>(m, "Dict_byteset8_float64");
    declare_dict_bitwise<std::array<char,8>, std::array<char,4>>(m, "Dict_byteset8_byteset4");
    declare_dict_bitwise<std::array<char,8>, std::array<char,8>>(m, "Dict_byteset8_byteset8");
    declare_dict_bitwise<std::array<char,8>, std::array<char,12>>(m, "Dict_byteset8_byteset12");
    declare_dict_bitwise<std::array<char,8>, std::array<char,16>>(m, "Dict_byteset8_byteset16");
    declare_dict_default<std::array<char,12>, uint8_t>(m, "Dict_byteset12_uint8");
    declare_dict_default<std::array<char,12>, uint16_t>(m, "Dict_byteset12_uint16");
    declare_dict_default<std::array<char,12>, uint32_t>(m, "Dict_byteset12_uint32");
    declare_dict_default<std::array<char,12>, uint64_t>(m, "Dict_byteset12_uint64");
    declare_dict_default<std::array<char,12>, int8_t>(m, "Dict_byteset12_int8");
    declare_dict_default<std::array<char,12>, int16_t>(m, "Dict_byteset12_int16");
    declare_dict_default<std::array<char,12>, int32_t>(m, "Dict_byteset12_int32");
    declare_dict_default<std::array<char,12>, int64_t>(m, "Dict_byteset12_int64");
    declare_dict_default<std::array<char,12>, float>(m, "Dict_byteset12_float32");
    declare_dict_default<std::array<char,12>, double>(m, "Dict_byteset12_float64");
    declare_dict_bitwise<std::array<char,12>, std::array<char,4>>(m, "Dict_byteset12_byteset4");
    declare_dict_bitwise<std::array<char,12>, std::array<char,8>>(m, "Dict_byteset12_byteset8");
    declare_dict_bitwise<std::array<char,12>, std::array<char,12>>(m, "Dict_byteset12_byteset12");
    declare_dict_bitwise<std::array<char,12>, std::array<char,16>>(m, "Dict_byteset12_byteset16");
    declare_dict_default<std::array<char,16>, uint8_t>(m, "Dict_byteset16_uint8");
    declare_dict_default<std::array<char,16>, uint16_t>(m, "Dict_byteset16_uint16");
    declare_dict_default<std::array<char,16>, uint32_t>(m, "Dict_byteset16_uint32");
    declare_dict_default<std::array<char,16>, uint64_t>(m, "Dict_byteset16_uint64");
    declare_dict_default<std::array<char,16>, int8_t>(m, "Dict_byteset16_int8");
    declare_dict_default<std::array<char,16>, int16_t>(m, "Dict_byteset16_int16");
    declare_dict_default<std::array<char,16>, int32_t>(m, "Dict_byteset16_int32");
    declare_dict_default<std::array<char,16>, int64_t>(m, "Dict_byteset16_int64");
    declare_dict_default<std::array<char,16>, float>(m, "Dict_byteset16_float32");
    declare_dict_default<std::array<char,16>, double>(m, "Dict_byteset16_float64");
    declare_dict_bitwise<std::array<char,16>, std::array<char,4>>(m, "Dict_byteset16_byteset4");
    declare_dict_bitwise<std::array<char,16>, std::array<char,8>>(m, "Dict_byteset16_byteset8");
    declare_dict_bitwise<std::array<char,16>, std::array<char,12>>(m, "Dict_byteset16_byteset12");
    declare_dict_bitwise<std::array<char,16>, std::array<char,16>>(m, "Dict_byteset16_byteset16");

    declare_set<uint32_t>(m, "Set_uint32");
    declare_set<uint64_t>(m, "Set_uint64");
    declare_set<int32_t>(m, "Set_int32");
    declare_set<int64_t>(m, "Set_int64");
    declare_set<std::array<char,4>>(m, "Set_byteset4");
    declare_set<std::array<char,8>>(m, "Set_byteset8");
    declare_set<std::array<char,12>>(m, "Set_byteset12");
    declare_set<std::array<char,16>>(m, "Set_byteset16");
}
